# SPDX-FileCopyrightText: 2020, 2021 Romain Vigier <contact AT romainvigier.fr>
# SPDX-License-Identifier: GPL-3.0-or-later

FROM debian:stable-slim

RUN apt update \
	&& apt install --no-install-recommends -y gettext libglib2.0-bin libglib2.0-dev-bin meson zip gzip brotli
